ktor:
  application:
    modules:
      - com.shape.games.ApplicationKt.module
  deployment:
    port: 8080

weather:
  provider:
    type: "OPENWEATHERMAP"  # OPENWEATHERMAP, ACCUWEATHER, WEATHERAPI, DARK_SKY, WEATHERBIT
    fallbackEnabled: false
    fallbackProvider: null

openweathermap:
  apiKey: "84122ac0f70cdf7276c1a457f6a44b37"
  baseUrl: "https://api.openweathermap.org"
  timeoutMs: 30000

rateLimit:
  algorithm: "TOKEN_BUCKET"  # TOKEN_BUCKET, SLIDING_WINDOW, FIXED_WINDOW, LEAKY_BUCKET
  maxRequestsPerDay: 10000
  windowSizeDays: 1
  burstAllowance: 0.2  # 20% burst allowance
  refillRate: null  # requests per second (auto-calculated if null)

cache:
  weather:
    provider: "CAFFEINE"  # CAFFEINE, REDIS, HAZELCAST, EHCACHE, MEMORY
    durationMinutes: 15
  forecast:
    provider: "CAFFEINE"
    durationMinutes: 60
  location:
    provider: "CAFFEINE"
    durationMinutes: 1440  # 24 hours
  maxCacheSize: 1000