ktor:
  application:
    modules:
      - com.shape.games.ApplicationKt.module
  deployment:
    port: 8080

weather:
  provider:
    type: "OPENWEATHERMAP"
    fallbackEnabled: false
    fallbackProvider: null

openweathermap:
  apiKey: "84122ac0f70cdf7276c1a457f6a44b37"
  baseUrl: "https://api.openweathermap.org"
  timeoutMs: 30000

cache:
  weather:
    provider: "CAFFEINE"  # CAFFEINE, REDIS, HAZELCAST, EHCACHE, MEMORY
    durationMinutes: 15
  forecast:
    provider: "CAFFEINE"
    durationMinutes: 60
  location:
    provider: "CAFFEINE"
    durationMinutes: 1440  # 24 hours
  maxCacheSize: 1000

validation:
  maxLocationsPerRequest: 50
  minTemperatureThreshold: -100.0
  maxTemperatureThreshold: 100.0
  maxReasonableTemperature: 1000.0
  absoluteZeroCelsius: -273.15

rateLimit:
  globalDailyLimit: 9000
  perUserHourlyLimit: 100
  burstLimit: 20
  burstWindowMinutes: 5

api:
  defaultTemperatureUnit: "celsius"
  defaultForecastDays: 5
  cacheNamespaces:
    weather: "weather"
    forecast: "forecast"
    location: "location"